name: Pull Request

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".vscode/**"
      - ".idea/**"

permissions:
  contents: read
  packages: read

jobs:
  build-dapp:
    name: Dapp
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./src/dapp
      run-build: true
      audit-script: npm run audit --audit-level=high
  build-xgov-dapp:
    name: xGov Dapp
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./src/xgov-dapp
      pre-run-script: cd ../dapp && npm ci
      audit-script: npm run audit --audit-level=high
      run-dispatch: true
    secrets:
      chromatic-token: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      npm-auth-token: ${{ secrets.GITHUB_TOKEN }}
  build-api:
    name: Api
    uses: ./.github/workflows/node-ci.yml
    with:
      node-version: 18.x
      working-directory: ./src/voting-metadata-api
      run-build: true
      audit-script: npm run audit --audit-level=high
  build-algorand:
    name: Algorand build
    uses: ./.github/workflows/smart-contract-ci.yml
    with:
      working-directory: ./src/algorand
  build-infrastructure:
    name: Infrastructure
    uses: ./.github/workflows/node-ci.yml
    with:
      working-directory: ./infrastructure
      run-build: true
      audit-script: npm run audit --audit-level=high
